# Build stage
FROM openjdk:11 AS build
WORKDIR /app
COPY . .
RUN ./gradlew clean build -x test

# Package stage
FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /app/build/libs/service-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]