export const LOAD_PLACE_FAIL = "LOAD_PLACE_FAIL";
export const LOAD_PLACE_SUCCESS = "LOAD_PLACE_SUCCESS";
export const LOAD_PLACE_ID_FAIL = "LOAD_PLACE_ID_FAIL";
export const LOAD_PLACE_ID_SUCCESS = "LOAD_PLACE_ID_SUCCESS";