export const LOAD_PLACE_FAIL = "LOAD_PLACE_FAIL";
export const LOAD_PLACE_SUCCESS = "LOAD_PLACE_SUCCESS";
export const LOAD_PLACES_FAIL = "LOAD_PLACES_FAIL";
export const LOAD_PLACES_SUCCESS = "LOAD_PLACES_SUCCESS";