export const LOAD_FAV_SUCCESS = 'LOAD_FAV_SUCCEESS';
export const LOAD_FAV_FAIL = 'LOAD_FAV_FAIL';
export const ENROLL_FAV_SUCCESS = 'ENROLL_FAV_SUCCEESS';
export const ENROLL_FAV_FAIL = 'ENROLL_FAV_FAIL';
export const DELETE_FAV_SUCCESS = 'DELETE_FAV_SUCCEESS';
export const DELETE_FAV_FAIL = 'DELETE_FAV_FAIL';