export const GET_FAV_SUCCESS = 'GET_FAV_SUCCEESS';
export const GET_FAV_FAIL = 'GET_FAV_FAIL';
export const ENROLL_FAV_SUCCESS = 'ENROLL_FAV_SUCCEESS';
export const ENROLL_FAV_FAIL = 'ENROLL_FAV_FAIL';
export const DELETE_FAV_SUCCESS = 'DELETE_FAV_SUCCEESS';
export const DELETE_FAV_FAIL = 'DELETE_FAV_FAIL';
// 지우기
// export const SET_FAV_LOADING = 'SET_FAV_LOADING';
// export const REMOVE_FAV_LOADING = 'REMOVE_FAV_LOADING';
// export const RESET_GET_FAV_SUCCESS = 'RESET_GET_FAV_SUCCESS';
