export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';

export const CHANGE_TOGGLE_NOT_FOR_USER_SUCCESS = 'CHANGE_TOGGLE_NOT_FOR_USER_SUCCESS';
export const CHANGE_TOGGLE_NOT_FOR_USER_FAIL = 'CHANGE_TOGGLE_NOT_FOR_USER_FAIL';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const FIND_USERNAME_SUCCESS = 'FIND_USERNAME_SUCCESS';
export const FIND_USERNAME_FAIL = 'FIND_USERNAME_FAIL';