export const SIGNUP_EMAIL_SEND_SUCCESS= 'SIGNUP_EMAIL_SEND_SUCCESS';
export const SIGNUP_EMAIL_SEND_FAIL = 'SIGNUP_EMAIL_SEND_FAIL';

export const SIGNUP_EMAIL_CHECK_SUCCESS = 'SIGNUP_EMAIL_CHECK_SUCCESS';
export const SIGNUP_EMAIL_CHECK_FAIL = 'SIGNUP_EMAIL_CHECK_FAIL';

export const PASSWORD_EMAIL_SEND_SUCCESS= 'INIT_EMAIL_SEND_SUCCESS';
export const PASSWORD_EMAIL_SEND_FAIL = 'INIT_EMAIL_SEND_FAIL';

export const PASSWORD_EMAIL_CHECK_SUCCESS = 'INIT_EMAIL_CHECK_SUCCESS';
export const PASSWORD_EMAIL_CHECK_FAIL = 'INIT_EMAIL_CHECK_FAIL';

export const USERNAME_EMAIL_SEND_SUCCESS= 'USERNAME_EMAIL_SEND_SUCCESS';
export const USERNAME_EMAIL_SEND_FAIL = 'USERNAME_EMAIL_SEND_FAIL';

export const USERNAME_EMAIL_CHECK_SUCCESS = 'USERNAME_EMAIL_CHECK_SUCCESS';
export const USERNAME_EMAIL_CHECK_FAIL = 'USERNAME_EMAIL_CHECK_FAIL';