export const LOAD_PUSHTOKEN_SUCCESS = "LOAD_PUSHTOKEN_SUCCESS";
export const LOAD_PUSHTOKEN_FAIL = "LOAD_PUSHTOKEN_FAIL";
export const ENROLL_PUSHTOKEN_SUCCESS = "ENROLL_PUSHTOKEN_SUCCESS";
export const ENROLL_PUSHTOKEN_FAIL = "ENROLL_PUSHTOKEN_FAIL";
export const MODIFY_PUSHTOKEN_SUCCESS = "MODIFY_PUSHTOKEN_SUCCESS";
export const MODIFY_PUSHTOKEN_FAIL = "MODIFY_PUSHTOKEN_FAIL";