export const SET_MAP_SUCCESS = "SET_MAP_SUCCESS";
export const SET_MAP_FAIL = "SET_MAP_FAIL";
export const SET_MAP_SCRIPT_SUCCESS = "SET_MAP_SCRIPT_SUCCESS";
export const SET_MAP_SCRIPT_FAIL = "SET_MAP_SCRIPT_FAIL";