export const LOAD_APPOINTMENT_SUCCESS = 'LOAD_APPOINTMENT_SUCCESS';
export const LOAD_APPOINTMENT_FAIL = 'LOAD_APPOINTMENT_FAIL';
export const ENROLL_APPOINTMENT_SUCCESS = 'ENROLL_APPOINTMENT_SUCCESS';
export const ENROLL_APPOINTMENT_FAIL = 'ENROLL_APPOINTMENT_FAIL';
export const MODIFY_APPOINTMENT_SUCCESS = 'MODIFY_APPOINTMENT_SUCCESS';
export const MODIFY_APPOINTMENT_FAIL = 'MODIFY_APPOINTMENT_FAIL';