export const ADD_MATCHING_INFO_SUCCESS = 'ADD_MATCHING_INFO_SUCCESS';
export const ADD_MATCHING_INFO_FAIL = 'ADD_MATCHING_INFO_FAIL';

export const LOAD_MATCHING_INFO_SUCCESS = 'LOAD_MATCHING_INFO_SUCCESS';
export const LOAD_MATCHING_INFO_FAIL = 'LOAD_MATCHING_INFO_FAIL';

export const CHANGE_MATCHING_STATUS_SUCCESS = 'CHANGE_MATCHING_STATUS_SUCCESS';
export const CHANGE_MATCHING_STATUS_FAIL = 'CHANGE_MATCHING_STATUS_FAIL';

export const CHANGE_MATCHING_INFO_SUCCESS = 'CHANGE_MATCHING_INFO_SUCCESS';
export const CHANGE_MATCHING_INFO_FAIL = 'CHANGE_MATCHING_INFO_FAIL';

export const CLEAR_MATCHING_SUCCESS = 'CLEAR_MATCHING_SUCCESS';
export const CLEAR_MATCHING_FAIL = 'CLEAR_MATCHING_FAIL';