export const LOAD_COMMENT_FAIL = "LOAD_COMMENT_FAIL";
export const LOAD_COMMENT_SUCCESS = "LOAD_COMMENT_SUCCESS";

export const LOAD_ALL_COMMENTS_FAIL = "LOAD_ALL_COMMENTS_FAIL";
export const LOAD_ALL_COMMENTS_SUCCESS = "LOAD_ALL_COMMENTS_SUCCESS";

export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";

export const ENROLL_COMMENT_FAIL = "ENROLL_COMMENT_FAIL";
export const ENROLL_COMMENT_SUCCESS = "ENROLL_COMMENT_SUCCESS";

export const MODIFY_COMMENT_FAIL = "MODIFY_COMMENT_FAIL";
export const MODIFY_COMMENT_SUCCESS = "MODIFY_COMMENT_SUCCESS";

export const ENROLL_REPLY_FAIL = "ENROLL_REPLY_FAIL";
export const ENROLL_REPLY_SUCCESS = "ENROLL_REPLY_SUCCESS";

export const CLEAR_PREV_COMMENT = "CLEAR_PREV_COMMENT";

export const LIKE_COMMENT_FAIL = "LIKE_COMMENT_FAIL";
export const LIKE_COMMENT_SUCCESS = "LIKE_COMMENT_SUCCESS";
