export const LOAD_MENU_FAIL = "LOAD_MENU_FAIL";
export const LOAD_MENU_SUCCESS = "LOAD_MENU_SUCCESS";

export const ENROLL_MENU_FAIL = "ENROLL_MENU_FAIL";
export const ENROLL_MENU_SUCCESS = "ENROLL_MENU_SUCCESS";

export const MODIFY_MENU_FAIL = "MODIFY_MENU_FAIL";
export const MODIFY_MENU_SUCCESS = "MODIFY_MENU_SUCCESS";

export const DELETE_MENU_FAIL = "DELETE_MENU_FAIL";
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS";