export const API_URL = process.env.NEXT_PUBLIC_API_URL;
export const KAKAOMAP_APPKEY = process.env.NEXT_PUBLIC_KAKAOMAP_APPKEY;
export const WEB_PUSH_PUBLIC_KEY = "BJkNh3LjryGnKrmWZCY_fAebZqGPhtuzBZCBBoB7lPh54M1raOJGfATpy0X7BpVahZJXk6Iq6XFTxM4STBMSFTY";
export const GOOGLE_ANALYTICS = "G-0H1CX4383K";