export const LOAD_NOTICE_FAIL = "LOAD_NOTICE_FAIL";
export const LOAD_NOTICE_SUCCESS = "LOAD_NOTICE_SUCCESS";

export const LOAD_NOTICES_FAIL = "LOAD_NOTICES_FAIL";
export const LOAD_NOTICES_SUCCESS = "LOAD_NOTICES_SUCCESS";

export const DELETE_NOTICE_FAIL = "DELETE_NOTICE_FAIL";
export const DELETE_NOTICE_SUCCESS = "DELETE_NOTICE_SUCCESS";

export const MODIFY_NOTICE_SUCCESS = 'MODIFY_NOTICE_SUCCESS';
export const MODIFY_NOTICE_FAIL = 'MODIFY_NOTICE_FAIL';

export const ENROLL_NOTICE_SUCCESS = 'ENROLL_NOTICE_SUCCESS';
export const ENROLL_NOTICE_FAIL = 'ENROLL_NOTICE_FAIL';

export const READ_NOTICE_SUCCESS = 'READ_NOTICE_SUCCESS';
export const READ_NOTICE_FAIL = 'READ_NOTICE_FAIL';

export const GET_REALTIME_NOTICE_ALARM_SUCCESS = 'GET_REALTIME_NOTICE_ALARM_SUCCESS';
export const GET_REALTIME_NOTICE_ALARM_FAIL = 'GET_REALTIME_NOTICE_ALARM_FAIL';

export const GET_NOTICE_ALARM_SUBSCRIPTION_SUCCESS = 'GET_NOTICE_ALARM_SUBSCRIPTION_SUCCESS';
export const GET_NOTICE_ALARM_SUBSCRIPTION_FAIL = 'GET_NOTICE_ALARM_SUBSCRIPTION_FAIL';

export const GET_NOTICE_ALARM_INFO_SUCCESS = 'GET_NOTICE_ALARM_INFO_SUCCESS';
export const GET_NOTICE_ALARM_INFO_FAIL = 'GET_NOTICE_ALARM_INFO_FAIL';