export const LOAD_BlOCK_SUCCESS = 'LOAD_BLOCK_SUCCEESS';
export const LOAD_BLOCK_FAIL = 'LOAD_BLOCK_FAIL';
export const ENROLL_BLOCK_SUCCESS = 'ENROLL_BLOCK_SUCCESS';
export const ENROLL_BLOCK_FAIL = 'ENROLL_BLOCK_FAIL';
export const DELETE_BLOCK_SUCCESS = 'DELETE_BLOCK_SUCCESS';
export const DELETE_BLOCK_FAIL = 'DELETE_BLOCK_FAIL';