export const GET_REQUEST_ID_SUCCESS= 'GET_REQUEST_ID_SUCCESS';
export const GET_REQUEST_ID_FAIL = 'GET_REQUEST_ID_FAIL';

export const SEND_CHAT_MESSAGE_SUCCESS= 'SEND_CHAT_MESSAGE_SUCCESS';
export const SEND_CHAT_MESSAGE_FAIL = 'SEND_CHAT_MESSAGE_FAIL';

export const READ_CHAT_MESSAGE_SUCCESS = 'READ_CHAT_MESSAGE_SUCCESS';
export const READ_CHAT_MESSAGE_FAIL = 'READ_CHAT_MESSAGE_FAIL';

export const REQUEST_CHAT_SUCCESS = 'REQUEST_CHAT_SUCCESS';
export const REQUEST_CHAT_FAIL = 'REQUEST_CHAT_FAIL';

export const SET_USER_BLOCK_SUCCESS = 'SET_USER_BLOCK_SUCCESS';
export const SET_USER_BLOCK_FAIL = 'SET_USER_BLOCK_FAIL';

export const REPLY_CHAT_REQUEST_SUCCESS= 'REPLY_CHAT_REQUEST_SUCCESS';
export const REPLY_CHAT_REQUEST_FAIL = 'REPLY_CHAT_REQUEST_FAIL';

export const SET_CHAT_ALARM_SUCCESS = 'SET_CHAT_ALARM_SUCCESS';
export const SET_CHAT_ALARM_FAIL = 'SET_CHAT_ALARM_FAIL';

export const SET_MEET_TIME_SUCCESS = 'SET_MEET_TIME_SUCCESS';
export const SET_MEET_TIME_FAIL = 'SET_MEET_TIME_FAIL';

export const SET_MEET_PLACE_SUCCESS = 'SET_MEET_PLACE_SUCCESS';
export const SET_MEET_PLACE_FAIL = 'SET_MEET_PLACE_FAIL';

export const DELETE_MEET_TIME_SUCCESS = 'DELETE_MEET_TIME_SUCCESS';
export const DELETE_MEET_TIME_FAIL = 'DELETE_MEET_TIME_FAIL';

export const DELETE_MEET_PLACE_SUCCESS = 'DELETE_MEET_PLACE_SUCCESS';
export const DELETE_MEET_PLACE_FAIL = 'DELETE_MEET_PLACE_FAIL';

export const EXIT_CHAT_ROOM_SUCCESS = 'EXIT_CHAT_ROOM_SUCCESS';
export const EXIT_CHAT_ROOM_FAIL = 'EXIT_CHAT_ROOM_FAIL';

export const GET_REALTIME_REQUEST_SUCCESS = 'GET_REALTIME_REQUEST_SUCCESS';
export const GET_REALTIME_REQUEST_FAIL = 'GET_REALTIME_REQUEST_FAIL';

export const GET_REALTIME_USER_SUCCESS = 'GET_REALTIME_USER_SUCCESS';
export const GET_REALTIME_USER_FAIL = 'GET_REALTIME_USER_FAIL';

export const GET_REALTIME_SETTING_SUCCESS = 'GET_REALTIME_SETTING_SUCCESS';
export const GET_REALTIME_SETTING_FAIL = 'GET_REALTIME_SETTING_FAIL';

export const GET_REALTIME_MESSAGE_SUCCESS = 'GET_REALTIME_MESSAGE_SUCCESS';
export const GET_REALTIME_MESSAGE_FAIL = 'GET_REALTIME_MESSAGE_FAIL';

export const GET_REALTIME_ROOM_SUCCESS = 'GET_REALTIME_ROOM_SUCCESS';
export const GET_REALTIME_ROOM_FAIL = 'GET_REALTIME_ROOM_FAIL';

export const GET_REALTIME_ALARM_SUCCESS = 'GET_REALTIME_ALARM_SUCCESS';
export const GET_REALTIME_ALARM_FAIL = 'GET_REALTIME_ALARM_FAIL';

export const GET_CHAT_INFO_SUCCESS = 'GET_CHAT_INFO_SUCCESS';
export const GET_CHAT_INFO_FAIL = 'GET_CHAT_INFO_FAIL';

export const GET_CHAT_ROOM_INFO_SUCCESS = 'GET_CHAT_ROOM_INFO_SUCCESS';
export const GET_CHAT_ROOM_INFO_FAIL = 'GET_CHAT_ROOM_INFO_FAIL';

export const GET_CHAT_REQUEST_INFO_SUCCESS = 'GET_CHAT_REQUEST_INFO_SUCCESS';
export const GET_CHAT_REQUEST_INFO_FAIL = 'GET_CHAT_REQUEST_INFO_FAIL';

export const GET_ALARM_SUBSCRIPTION_SUCCESS = 'GET_ALARM_SUBSCRIPTION_SUCCESS';
export const GET_ALARM_SUBSCRIPTION_FAIL = 'GET_ALARM_SUBSCRIPTION_FAIL';

export const GET_CHAR_ALARM_INFO_SUCCESS = 'GET_CHAR_ALARM_INFO_SUCCESS';
export const GET_CHAR_ALARM_INFO_FAIL = 'GET_CHAR_ALARM_INFO_FAIL';

export const CLEAR_CHAT_SUCCESS = 'CLEAR_CHAT_SUCCESS';
export const CLEAR_CHAT_FAIL = 'CLEAR_CHAT_FAIL';

export const CLEAR_ROOM_LIST_SUCCESS = 'CLEAR_ROOM_LIST_SUCCESS';
export const CLEAR_ROOM_LIST_FAIL = 'CLEAR_ROOM_LIST_FAIL';

export const GET_CHAT_ROOM_FOR_NOT_USER_SUCCESS = 'GET_CHAT_ROOM_FOR_NOT_USER_SUCCESS';
export const GET_CHAT_ROOM_FOR_NOT_USER_FAIL = 'GET_CHAT_ROOM_FOR_NOT_USER_FAIL';

export const GET_CHAT_REQUEST_FOR_NOT_USER_SUCCESS = 'GET_CHAT_REQUEST_FOR_NOT_USER_SUCCESS';
export const GET_CHAT_REQUEST_FOR_NOT_USER_FAIL = 'GET_CHAT_REQUEST_FOR_NOT_USER_FAIL';

export const SET_USER_PROFILE_SUCCESS = 'SET_USER_PROFILE_SUCCESS';
export const SET_USER_PROFILE_FAIL = 'SET_USER_PROFILE_FAIL';

export const CLEAR_USER_PROFILE_SUCCESS = 'CLEAR_USER_PROFILE_SUCCESS';
export const CLEAR_USER_PROFILE_FAIL = 'CLEAR_USER_PROFILE_FAIL';