export const LOAD_REVIEW_FAIL = "LOAD_REVIEW_FAIL";
export const LOAD_REVIEW_SUCCESS = "LOAD_REVIEW_SUCCESS";

export const LOAD_REVIEWS_FAIL = "LOAD_REVIEWS_FAIL";
export const LOAD_REVIEWS_SUCCESS = "LOAD_REVIEWS_SUCCESS";

export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";

export const ENROLL_REVIEW_FAIL = "ENROLL_REVIEW_FAIL";
export const ENROLL_REVIEW_SUCCESS = "ENROLL_REVIEW_SUCCESS";

export const MODIFY_REVIEW_FAIL = "MODIFY_REVIEW_FAIL";
export const MODIFY_REVIEW_SUCCESS = "MODIFY_REVIEW_SUCCESS";