export const LOAD_MY_LIKE_SUCCESS = 'LOAD_MY_LIKE_SUCCEESS';
export const LOAD_MY_LIKE_FAIL = 'LOAD_MY_LIKE_FAIL';
export const ENROLL_LIKE_SUCCESS = 'ENROLL_LIKE_SUCCEESS';
export const ENROLL_LIKE_FAIL = 'ENROLL_LIKE_FAIL';
export const DELETE_LIKE_SUCCESS = 'DELETE_LIKE_SUCCEESS';
export const DELETE_LIKE_FAIL = 'DELETE_LIKE_FAIL';