export const ADD_MAGAZINE_SUCCESS = 'ADD_MAGAZINE_SUCCESS';
export const ADD_MAGAZINE_FAIL = 'ADD_MAGAZINE_FAIL';

export const LOAD_MAGAZINE_SUCCESS = 'LOAD_MAGAZINE_SUCCESS';
export const LOAD_MAGAZINE_FAIL = 'LOAD_MAGAZINE_FAIL';

export const LOAD_ALL_MAGAZINE_SUCCESS = 'LOAD_ALL_MAGAZINE_SUCCESS';
export const LOAD_ALL_MAGAZINE_FAIL = 'LOAD_ALL_MAGAZINE_FAIL';

export const CHANGE_MAGAZINE_SUCCESS = 'CHANGE_MAGAZINE_SUCCESS';
export const CHANGE_MAGAZINE_FAIL = 'CHANGE_MAGAZINE_FAIL';

export const DELETE_MAGAZINE_SUCCESS = 'DELETE_MAGAZINE_SUCCESS';
export const DELETE_MAGAZINE_FAIL = 'DELETE_MAGAZINE_FAIL';