export const LOAD_POST_FAIL = "LOAD_POST_FAIL";
export const LOAD_POST_SUCCESS = "LOAD_POST_SUCCESS";

export const LOAD_ALL_POSTS_FAIL = "LOAD_ALL_POSTS_FAIL";
export const LOAD_ALL_POSTS_SUCCESS = "LOAD_ALL_POSTS_SUCCESS";

export const LOAD_MY_POSTS_FAIL = "LOAD_MY_POSTS_FAIL";
export const LOAD_MY_POSTS_SUCCESS = "LOAD_MY_POSTS_SUCCESS";

export const LOAD_FAV_POSTS_FAIL = "LOAD_FAV_POSTS_FAIL";
export const LOAD_FAV_POSTS_SUCCESS = "LOAD_FAV_POSTS_SUCCESS";

export const DELETE_POST_FAIL = "DELETE_POST_FAIL";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

export const ENROLL_POST_FAIL = "ENROLL_POST_FAIL";
export const ENROLL_POST_SUCCESS = "ENROLL_POST_SUCCESS";

export const MODIFY_POST_FAIL = "MODIFY_POST_FAIL";
export const MODIFY_POST_SUCCESS = "MODIFY_POST_SUCCESS";

export const CLEAR_PREV_POST = "CLEAR_PREV_POST";